add_library(libSceNpCommerce SHARED EXCLUDE_FROM_ALL Export.cpp)
target_include_directories(libSceNpCommerce PRIVATE ${LIBS_INCLUDE_DIR})
configure_windows_unwind(libSceNpCommerce)

if(BUILD_TESTING)
    add_test_executable(guest_np_commerce_tests ${LIBS_INCLUDE_DIR}/tests/GuestNpCommerce.cpp)
    target_include_directories(guest_np_commerce_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_np_commerce_tests PRIVATE libSceNpCommerce libc)
    configure_windows_unwind(guest_np_commerce_tests)
    add_test(NAME guest_np_commerce COMMAND guest_np_commerce_tests)
    if(WIN32)
        set_tests_properties(guest_np_commerce PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libSceNpCommerce>")
    endif()
endif()
